version: '2'
services:
    db:
        image: postgres
        volumes:
          - /data/dock/hearthdeepweb/log/postgres/:/var/log/postgres
          - /data/dock/hearthdeepweb/postgres/:/var/lib/postgres
    web:
        build: .
        volumes:
            - .:/code
        entrypoint: ./docker-entrypoint.sh
        ports:
            - "8084:8000"
        depends_on:
            - db
