version: '2'
services:
    db:
        image: postgres
        volumes:
          - /data/dock/hearthdeepweb/postgres/log:/var/log/postgresql
          - /data/dock/hearthdeepweb/postgres/data:/var/lib/postgresql/data
    web:
        build: .
        volumes:
          - .:/code
          - /data/dock/hearthdeepweb/.ssh:/root/.ssh
        entrypoint: ./docker-entrypoint.sh
        ports:
            - "8084:8000"
        depends_on:
            - db
